export type AdminLocale = "en" | "es" | "ru";

export const adminLocales: { id: AdminLocale; flag: string; label: string }[] = [
  { id: "en", flag: "🇬🇧", label: "English" },
  { id: "es", flag: "🇪🇸", label: "Español" },
  { id: "ru", flag: "🇷🇺", label: "Русский" },
];

export function isAdminLocale(value: string | null | undefined): value is AdminLocale {
  return value === "en" || value === "es" || value === "ru";
}

const en = {
  title: "Admin Panel",
  house: "Tango Slavique Admin",
  denied: "Admin access is only available to authorized administrators.",
  back: "Back",
  myProfile: "My profile",
  language: "Language",
  save: "Save",
  saving: "Saving…",
  error: "Could not save",
  accessRequired: "Admin access required",
  loading: "Just a moment…",
  success: "Saved.",
  confirm: {
    published: "Article published.",
    unpublished: "Article unpublished.",
    deleted: "Deleted.",
    deletePost: "Delete this post?",
    unpublishPost: "Hide this post from the website?",
    publishContent: "Publish this text on the website?",
    discard: "Discard unsaved changes?",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    preview: "Preview",
    publish: "Publish",
    unpublish: "Unpublish",
    delete: "Delete",
    edit: "Edit",
    next: "Next",
    previous: "Previous",
    yes: "Yes",
    no: "No",
    close: "Close",
    upload: "Upload photo",
    uploading: "Uploading photo…",
    generating: "Preparing the text…",
  },
  nav: {
    dashboard: "Dashboard",
    applications: "Applications",
    profiles: "Profiles",
    photos: "Photos",
    matches: "Matches",
    blog: "Blog",
    content: "Website Content",
    notifications: "Notifications",
    notes: "Notes",
    settings: "Settings",
  },
  extra: {
    introductions: "Introductions",
    feedback: "Feedback",
    history: "History",
    users: "Users",
  },
  dash: {
    newApplications: "New Applications",
    profiles: "Profiles",
    photosWaiting: "Photos Waiting Review",
    blogDrafts: "Blog Drafts",
    notifications: "Notifications",
    waitingApplications: "Applications waiting",
    waitingPhotos: "Photos waiting",
    matches: "Matches",
  },
  actions: {
    approve: "Approve",
    reject: "Reject",
    needInfo: "Need info",
    hide: "Hide",
    useAnyway: "Use anyway",
    requestNew: "Request new photo",
    publish: "Publish",
    unpublish: "Unpublish",
    delete: "Delete",
    preview: "Preview",
    runMatching: "Run matching",
    rerun: "Re-run matching",
    addNote: "Add note",
    schedule: "Schedule",
    complete: "Complete",
    saveProfile: "Save profile",
    newBlog: "New Blog",
    saveDraft: "Save Draft",
    generateEn: "Prepare English",
    generateEs: "Prepare Spanish",
    sendInfo: "Send request",
  },
  filters: {
    pending: "Pending",
    needInfo: "Need information",
    approved: "Approved",
    rejected: "Rejected",
  },
  infoHint: "Write what information is needed. This message is sent to the applicant.",
  infoPlaceholder: "What information is required?",
  fields: {
    name: "Name",
    city: "City",
    about: "About",
    note: "Private note",
  },
  photo: {
    face: "Face visible",
    person: "Main person",
    quality: "Quality",
    yes: "yes",
    no: "no",
    decision: "Admin decision",
    annotation: "Review marks",
    unavailable: "AI review unavailable — please check this photo yourself.",
    waiting: "Waiting for review",
    aiRequired: "AI review required",
  },
  blog: {
    new: "New Blog",
    edit: "Edit",
    preview: "Preview",
    publish: "Publish",
    unpublish: "Unpublish",
    delete: "Delete",
    saveDraft: "Save Draft",
    cancel: "Cancel",
    original: "Original text",
    english: "English version",
    spanish: "Spanish version",
    photo: "Photo",
    title: "Title",
    body: "Text",
    placeholderOriginal: "Write the original text. The first line is the title.",
    placeholderEn: "English title on the first line, then the text.",
    placeholderEs: "Spanish title on the first line, then the text.",
    empty: "No blog posts yet.",
    saved: "Draft saved.",
    published: "Blog published successfully.",
    needPhoto: "Please add a photo.",
    needText: "Please add the blog text.",
    choosePhoto: "Choose photo",
    drafts: "Draft",
    publishedLabel: "Published",
    unpublishedLabel: "Unpublished",
  },
  content: {
    title: "Website Content",
    edit: "Edit",
    preview: "Preview",
    save: "Save",
    publish: "Publish",
    cancel: "Cancel",
    old: "Current",
    next: "New",
    empty: "No fields in this section.",
    saved: "Draft saved. Publish to show it on the website.",
    published: "Published on the website.",
    pickPage: "Choose a page",
    pickField: "Choose a field",
    english: "English",
    spanish: "Spanish",
    placeholder: "New text",
  },
  empty: {
    applications: "No applications yet.",
    profiles: "No profiles yet.",
    photos: "No photos yet.",
    matches: "No matches yet.",
    introductions: "No introductions yet.",
    feedback: "No feedback yet.",
    notifications: "No notifications yet.",
    history: "No admin actions yet.",
    blog: "No blog posts yet.",
    users: "No users yet.",
    notes: "No notes yet.",
    content: "No website fields yet.",
  },
  status: {
    new: "New",
    info_requested: "Needs info",
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    public: "Visible",
    hidden: "Hidden",
    draft: "Draft",
    published: "Published",
    unpublished: "Unpublished",
    archived: "Archived",
    proposed: "Proposed",
    saved: "Saved",
    waiting: "Waiting for review",
    AI_OK: "AI: OK",
    AI_WARNING: "AI: warning",
    REVIEW_REQUIRED: "AI review required",
    AI_UNAVAILABLE: "AI unavailable",
  },
  settingsHint: "Each administrator can choose their own language. It is saved for next time.",
};

export const adminCopy = {
  en,
  es: {
    ...en,
    title: "Panel de administración",
    house: "Admin Tango Slavique",
    denied: "El acceso de administración solo está disponible para administradores autorizados.",
    back: "Atrás",
    myProfile: "Mi perfil",
    language: "Idioma",
    save: "Guardar",
    saving: "Guardando…",
    error: "No se pudo guardar",
    accessRequired: "Se requiere acceso de administrador",
    loading: "Un momento…",
    success: "Guardado.",
    confirm: {
      published: "Artículo publicado.",
      unpublished: "Artículo oculto.",
      deleted: "Eliminado.",
      deletePost: "¿Eliminar esta publicación?",
      unpublishPost: "¿Ocultar esta publicación del sitio?",
      publishContent: "¿Publicar este texto en el sitio?",
      discard: "¿Descartar los cambios sin guardar?",
    },
    common: {
      save: "Guardar",
      cancel: "Cancelar",
      preview: "Vista previa",
      publish: "Publicar",
      unpublish: "Ocultar",
      delete: "Eliminar",
      edit: "Editar",
      next: "Siguiente",
      previous: "Anterior",
      yes: "Sí",
      no: "No",
      close: "Cerrar",
      upload: "Subir foto",
      uploading: "Subiendo foto…",
      generating: "Preparando el texto…",
    },
    nav: {
      dashboard: "Panel",
      applications: "Solicitudes",
      profiles: "Perfiles",
      photos: "Fotos",
      matches: "Encuentros",
      blog: "Blog",
      content: "Contenido del sitio",
      notifications: "Avisos",
      notes: "Notas",
      settings: "Ajustes",
    },
    extra: {
      introductions: "Presentaciones",
      feedback: "Valoraciones",
      history: "Historial",
      users: "Usuarios",
    },
    dash: {
      newApplications: "Nuevas solicitudes",
      profiles: "Perfiles",
      photosWaiting: "Fotos en revisión",
      blogDrafts: "Borradores del blog",
      notifications: "Avisos",
      waitingApplications: "Solicitudes pendientes",
      waitingPhotos: "Fotos pendientes",
      matches: "Encuentros",
    },
    actions: {
      approve: "Aprobar",
      reject: "Rechazar",
      needInfo: "Pedir info",
      hide: "Ocultar",
      useAnyway: "Usar igual",
      requestNew: "Pedir foto nueva",
      publish: "Publicar",
      unpublish: "Ocultar",
      delete: "Eliminar",
      preview: "Vista previa",
      runMatching: "Ejecutar matching",
      rerun: "Volver a emparejar",
      addNote: "Añadir nota",
      schedule: "Programar",
      complete: "Completar",
      saveProfile: "Guardar perfil",
      newBlog: "Nuevo blog",
      saveDraft: "Guardar borrador",
      generateEn: "Preparar inglés",
      generateEs: "Preparar español",
      sendInfo: "Enviar petición",
    },
    filters: {
      pending: "Pendientes",
      needInfo: "Falta información",
      approved: "Aprobadas",
      rejected: "Rechazadas",
    },
    infoHint: "Escriba qué información falta. Este mensaje se envía al solicitante.",
    infoPlaceholder: "¿Qué información se necesita?",
    fields: {
      name: "Nombre",
      city: "Ciudad",
      about: "Sobre la persona",
      note: "Nota privada",
    },
    photo: {
      face: "Rostro visible",
      person: "Persona principal",
      quality: "Calidad",
      yes: "sí",
      no: "no",
      decision: "Decisión del admin",
      annotation: "Marcas de revisión",
      unavailable: "La revisión con IA no está disponible. Revisa la foto tú mismo.",
      waiting: "Esperando revisión",
      aiRequired: "Revisión con IA necesaria",
    },
    blog: {
      new: "Nuevo blog",
      edit: "Editar",
      preview: "Vista previa",
      publish: "Publicar",
      unpublish: "Ocultar",
      delete: "Eliminar",
      saveDraft: "Guardar borrador",
      cancel: "Cancelar",
      original: "Texto original",
      english: "Versión en inglés",
      spanish: "Versión en español",
      photo: "Foto",
      title: "Título",
      body: "Texto",
      placeholderOriginal: "Escriba el texto original. La primera línea es el título.",
      placeholderEn: "Título en inglés en la primera línea, luego el texto.",
      placeholderEs: "Título en español en la primera línea, luego el texto.",
      empty: "Aún no hay artículos.",
      saved: "Borrador guardado.",
      published: "Artículo publicado.",
      needPhoto: "Añada una foto.",
      needText: "Añada el texto del artículo.",
      choosePhoto: "Elegir foto",
      drafts: "Borrador",
      publishedLabel: "Publicado",
      unpublishedLabel: "Oculto",
    },
    content: {
      title: "Contenido del sitio",
      edit: "Editar",
      preview: "Vista previa",
      save: "Guardar",
      publish: "Publicar",
      cancel: "Cancelar",
      old: "Actual",
      next: "Nuevo",
      empty: "No hay campos en esta sección.",
      saved: "Borrador guardado. Publíquelo para mostrarlo en el sitio.",
      published: "Publicado en el sitio.",
      pickPage: "Elija una página",
      pickField: "Elija un campo",
      english: "Inglés",
      spanish: "Español",
      placeholder: "Texto nuevo",
    },
    empty: {
      applications: "Aún no hay solicitudes.",
      profiles: "Aún no hay perfiles.",
      photos: "Aún no hay fotos.",
      matches: "Aún no hay encuentros.",
      introductions: "Aún no hay presentaciones.",
      feedback: "Aún no hay valoraciones.",
      notifications: "Aún no hay avisos.",
      history: "Aún no hay acciones de admin.",
      blog: "Aún no hay artículos.",
      users: "Aún no hay usuarios.",
      notes: "Aún no hay notas.",
      content: "Aún no hay campos del sitio.",
    },
    status: {
      new: "Nueva",
      info_requested: "Falta información",
      approved: "Aprobada",
      rejected: "Rechazada",
      pending: "Pendiente",
      public: "Visible",
      hidden: "Oculto",
      draft: "Borrador",
      published: "Publicado",
      unpublished: "Oculto",
      archived: "Archivado",
      proposed: "Propuesto",
      saved: "Guardada",
      waiting: "Esperando revisión",
      AI_OK: "IA: bien",
      AI_WARNING: "IA: aviso",
      REVIEW_REQUIRED: "Revisión con IA necesaria",
      AI_UNAVAILABLE: "IA no disponible",
    },
    settingsHint: "Cada administrador puede elegir su idioma. Se guarda para la próxima vez.",
  },
  ru: {
    ...en,
    title: "Админ-панель",
    house: "Админ Tango Slavique",
    denied: "Доступ в админ-панель есть только у уполномоченных администраторов.",
    back: "Назад",
    myProfile: "Мой профиль",
    language: "Язык",
    save: "Сохранить",
    saving: "Сохранение…",
    error: "Не удалось сохранить",
    accessRequired: "Нужен доступ администратора",
    loading: "Минуту…",
    success: "Сохранено.",
    confirm: {
      published: "Статья опубликована.",
      unpublished: "Статья снята с публикации.",
      deleted: "Удалено.",
      deletePost: "Удалить эту запись?",
      unpublishPost: "Снять запись с сайта?",
      publishContent: "Опубликовать этот текст на сайте?",
      discard: "Отменить несохранённые изменения?",
    },
    common: {
      save: "Сохранить",
      cancel: "Отмена",
      preview: "Предпросмотр",
      publish: "Опубликовать",
      unpublish: "Снять с публикации",
      delete: "Удалить",
      edit: "Редактировать",
      next: "Далее",
      previous: "Назад",
      yes: "Да",
      no: "Нет",
      close: "Закрыть",
      upload: "Загрузить фото",
      uploading: "Загрузка фото…",
      generating: "Готовим текст…",
    },
    nav: {
      dashboard: "Панель управления",
      applications: "Заявки",
      profiles: "Профили",
      photos: "Фотографии",
      matches: "Пары",
      blog: "Блог",
      content: "Контент сайта",
      notifications: "Уведомления",
      notes: "Заметки",
      settings: "Настройки",
    },
    extra: {
      introductions: "Знакомства",
      feedback: "Отзывы",
      history: "История",
      users: "Пользователи",
    },
    dash: {
      newApplications: "Новые заявки",
      profiles: "Профили",
      photosWaiting: "Фотографии ждут проверки",
      blogDrafts: "Черновики блога",
      notifications: "Уведомления",
      waitingApplications: "Заявки на проверке",
      waitingPhotos: "Фото на проверке",
      matches: "Пары",
    },
    actions: {
      approve: "Одобрить",
      reject: "Отклонить",
      needInfo: "Нужна информация",
      hide: "Скрыть",
      useAnyway: "Оставить",
      requestNew: "Попросить новое фото",
      publish: "Опубликовать",
      unpublish: "Снять с публикации",
      delete: "Удалить",
      preview: "Предпросмотр",
      runMatching: "Запустить подбор",
      rerun: "Повторить подбор",
      addNote: "Добавить заметку",
      schedule: "Назначить",
      complete: "Завершить",
      saveProfile: "Сохранить профиль",
      newBlog: "Новый блог",
      saveDraft: "Сохранить черновик",
      generateEn: "Подготовить английский",
      generateEs: "Подготовить испанский",
      sendInfo: "Отправить запрос",
    },
    filters: {
      pending: "Ожидают",
      needInfo: "Нужна информация",
      approved: "Одобрены",
      rejected: "Отклонены",
    },
    infoHint: "Напишите, какая информация нужна. Это сообщение уйдёт заявителю.",
    infoPlaceholder: "Какая информация нужна?",
    fields: {
      name: "Имя",
      city: "Город",
      about: "О человеке",
      note: "Личная заметка",
    },
    photo: {
      face: "Лицо видно",
      person: "Главный человек",
      quality: "Качество",
      yes: "да",
      no: "нет",
      decision: "Решение администратора",
      annotation: "Пометки проверки",
      unavailable: "Проверка ИИ недоступна. Просмотрите фото самостоятельно.",
      waiting: "Ожидает проверки",
      aiRequired: "Требуется проверка AI",
    },
    blog: {
      new: "Новый блог",
      edit: "Редактировать",
      preview: "Предпросмотр",
      publish: "Опубликовать",
      unpublish: "Снять с публикации",
      delete: "Удалить",
      saveDraft: "Сохранить черновик",
      cancel: "Отмена",
      original: "Исходный текст",
      english: "Английская версия",
      spanish: "Испанская версия",
      photo: "Фото",
      title: "Заголовок",
      body: "Текст",
      placeholderOriginal: "Напишите исходный текст. Первая строка — заголовок.",
      placeholderEn: "Английский заголовок в первой строке, затем текст.",
      placeholderEs: "Испанский заголовок в первой строке, затем текст.",
      empty: "Записей пока нет.",
      saved: "Черновик сохранён.",
      published: "Блог опубликован.",
      needPhoto: "Добавьте фотографию.",
      needText: "Добавьте текст записи.",
      choosePhoto: "Выбрать фото",
      drafts: "Черновик",
      publishedLabel: "Опубликовано",
      unpublishedLabel: "Снято с публикации",
    },
    content: {
      title: "Контент сайта",
      edit: "Редактировать",
      preview: "Предпросмотр",
      save: "Сохранить",
      publish: "Опубликовать",
      cancel: "Отмена",
      old: "Сейчас",
      next: "Новый текст",
      empty: "В этом разделе нет полей.",
      saved: "Черновик сохранён. Опубликуйте, чтобы показать на сайте.",
      published: "Опубликовано на сайте.",
      pickPage: "Выберите страницу",
      pickField: "Выберите поле",
      english: "Английский",
      spanish: "Испанский",
      placeholder: "Новый текст",
    },
    empty: {
      applications: "Заявок пока нет.",
      profiles: "Профилей пока нет.",
      photos: "Фотографий пока нет.",
      matches: "Пар пока нет.",
      introductions: "Знакомств пока нет.",
      feedback: "Отзывов пока нет.",
      notifications: "Уведомлений пока нет.",
      history: "Действий администратора пока нет.",
      blog: "Записей блога пока нет.",
      users: "Пользователей пока нет.",
      notes: "Заметок пока нет.",
      content: "Полей сайта пока нет.",
    },
    status: {
      new: "Новая",
      info_requested: "Нужна информация",
      approved: "Одобрено",
      rejected: "Отклонено",
      pending: "На проверке",
      public: "Виден",
      hidden: "Скрыт",
      draft: "Черновик",
      published: "Опубликовано",
      unpublished: "Снято с публикации",
      archived: "В архиве",
      proposed: "Предложена",
      saved: "Сохранена",
      waiting: "Ожидает проверки",
      AI_OK: "ИИ: норма",
      AI_WARNING: "ИИ: предупреждение",
      REVIEW_REQUIRED: "Требуется проверка AI",
      AI_UNAVAILABLE: "ИИ недоступен",
    },
    settingsHint: "Каждый администратор выбирает свой язык. Выбор сохраняется.",
  },
} as const;

export type AdminCopy = (typeof adminCopy)[AdminLocale];

export function statusLabel(t: AdminCopy, status?: string | null) {
  if (!status) return "—";
  const map = t.status as Record<string, string>;
  return map[status] || status.replace(/_/g, " ");
}
