export type AdminLocale = "en" | "es" | "ru";

export const adminLocales: { id: AdminLocale; flag: string; label: string }[] = [
  { id: "en", flag: "🇬🇧", label: "English" },
  { id: "es", flag: "🇪🇸", label: "Español" },
  { id: "ru", flag: "🇷🇺", label: "Русский" },
];

export function isAdminLocale(value: string | null | undefined): value is AdminLocale {
  return value === "en" || value === "es" || value === "ru";
}

const en = {
  title: "Admin Panel",
  house: "Tango Slavique Admin",
  denied: "Admin access is only available to authorized administrators.",
  back: "Back",
  myProfile: "My profile",
  language: "Language",
  save: "Save",
  saving: "Saving…",
  error: "Could not save",
  accessRequired: "Admin access required",
  loading: "Just a moment…",
  nav: {
    dashboard: "Dashboard",
    applications: "Applications",
    profiles: "Profiles",
    photos: "Photos",
    matches: "Matches",
    blog: "Blog",
    notifications: "Notifications",
    notes: "Notes",
    settings: "Settings",
  },
  extra: {
    introductions: "Introductions",
    feedback: "Feedback",
    history: "History",
    users: "Users",
  },
  dash: {
    waitingApplications: "Applications waiting",
    waitingPhotos: "Photos waiting",
    profiles: "Profiles",
    matches: "Matches",
    notifications: "Notifications",
  },
  actions: {
    approve: "Approve",
    reject: "Reject",
    needInfo: "Need info",
    hide: "Hide",
    useAnyway: "Use anyway",
    requestNew: "Request new photo",
    publish: "Publish",
    unpublish: "Unpublish",
    delete: "Delete",
    preview: "Preview",
    runMatching: "Run matching",
    rerun: "Re-run matching",
    addNote: "Add note",
    schedule: "Schedule",
    complete: "Complete",
    saveProfile: "Save profile",
  },
  fields: {
    name: "Name",
    city: "City",
    about: "About",
    note: "Private note",
  },
  photo: {
    face: "Face visible",
    person: "Main person",
    quality: "Quality",
    yes: "yes",
    no: "no",
    decision: "Admin decision",
    annotation: "Review marks",
    unavailable: "AI review unavailable — please check this photo yourself.",
  },
  empty: {
    applications: "No applications yet.",
    profiles: "No profiles yet.",
    photos: "No photos yet.",
    matches: "No matches yet.",
    introductions: "No introductions yet.",
    feedback: "No feedback yet.",
    notifications: "No notifications yet.",
    history: "No admin actions yet.",
    blog: "No blog drafts yet.",
    users: "No users yet.",
    notes: "No notes yet.",
  },
  status: {
    new: "New",
    info_requested: "Needs info",
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    public: "Visible",
    hidden: "Hidden",
    draft: "Draft",
    published: "Published",
    proposed: "Proposed",
    saved: "Saved",
    AI_OK: "AI: OK",
    AI_WARNING: "AI: warning",
    REVIEW_REQUIRED: "Needs review",
    AI_UNAVAILABLE: "AI unavailable",
  },
  confirm: {
    published: "Article published.",
    unpublished: "Article unpublished.",
    deleted: "Deleted.",
  },
  settingsHint: "Each administrator can choose their own language. It is saved for next time.",
};

export const adminCopy = {
  en,
  es: {
    ...en,
    title: "Panel de administración",
    house: "Admin Tango Slavique",
    denied: "El acceso de administración solo está disponible para administradores autorizados.",
    back: "Atrás",
    myProfile: "Mi perfil",
    language: "Idioma",
    save: "Guardar",
    saving: "Guardando…",
    error: "No se pudo guardar",
    accessRequired: "Se requiere acceso de administrador",
    loading: "Un momento…",
    nav: {
      dashboard: "Inicio",
      applications: "Solicitudes",
      profiles: "Perfiles",
      photos: "Fotos",
      matches: "Encuentros",
      blog: "Blog",
      notifications: "Avisos",
      notes: "Notas",
      settings: "Ajustes",
    },
    extra: {
      introductions: "Presentaciones",
      feedback: "Valoraciones",
      history: "Historial",
      users: "Usuarios",
    },
    dash: {
      waitingApplications: "Solicitudes pendientes",
      waitingPhotos: "Fotos pendientes",
      profiles: "Perfiles",
      matches: "Encuentros",
      notifications: "Avisos",
    },
    actions: {
      approve: "Aprobar",
      reject: "Rechazar",
      needInfo: "Pedir info",
      hide: "Ocultar",
      useAnyway: "Usar igual",
      requestNew: "Pedir foto nueva",
      publish: "Publicar",
      unpublish: "Despublicar",
      delete: "Eliminar",
      preview: "Vista previa",
      runMatching: "Ejecutar matching",
      rerun: "Volver a emparejar",
      addNote: "Añadir nota",
      schedule: "Programar",
      complete: "Completar",
      saveProfile: "Guardar perfil",
    },
    fields: {
      name: "Nombre",
      city: "Ciudad",
      about: "Sobre la persona",
      note: "Nota privada",
    },
    photo: {
      face: "Rostro visible",
      person: "Persona principal",
      quality: "Calidad",
      yes: "sí",
      no: "no",
      decision: "Decisión del admin",
      annotation: "Marcas de revisión",
      unavailable: "La revisión con IA no está disponible. Revisa la foto tú mismo.",
    },
    empty: {
      applications: "Aún no hay solicitudes.",
      profiles: "Aún no hay perfiles.",
      photos: "Aún no hay fotos.",
      matches: "Aún no hay encuentros.",
      introductions: "Aún no hay presentaciones.",
      feedback: "Aún no hay valoraciones.",
      notifications: "Aún no hay avisos.",
      history: "Aún no hay acciones de admin.",
      blog: "Aún no hay borradores.",
      users: "Aún no hay usuarios.",
      notes: "Aún no hay notas.",
    },
    status: {
      new: "Nueva",
      info_requested: "Falta información",
      approved: "Aprobada",
      rejected: "Rechazada",
      pending: "Pendiente",
      public: "Visible",
      hidden: "Oculto",
      draft: "Borrador",
      published: "Publicado",
      proposed: "Propuesto",
      saved: "Guardada",
      AI_OK: "IA: bien",
      AI_WARNING: "IA: aviso",
      REVIEW_REQUIRED: "Revisar",
      AI_UNAVAILABLE: "IA no disponible",
    },
    confirm: {
      published: "Artículo publicado.",
      unpublished: "Artículo despublicado.",
      deleted: "Eliminado.",
    },
    settingsHint: "Cada administrador puede elegir su idioma. Se guarda para la próxima vez.",
  },
  ru: {
    ...en,
    title: "Админ-панель",
    house: "Админ Tango Slavique",
    denied: "Доступ в админ-панель есть только у уполномоченных администраторов.",
    back: "Назад",
    myProfile: "Мой профиль",
    language: "Язык",
    save: "Сохранить",
    saving: "Сохранение…",
    error: "Не удалось сохранить",
    accessRequired: "Нужен доступ администратора",
    loading: "Минуту…",
    nav: {
      dashboard: "Обзор",
      applications: "Заявки",
      profiles: "Профили",
      photos: "Фото",
      matches: "Пары",
      blog: "Блог",
      notifications: "Уведомления",
      notes: "Заметки",
      settings: "Настройки",
    },
    extra: {
      introductions: "Знакомства",
      feedback: "Отзывы",
      history: "История",
      users: "Пользователи",
    },
    dash: {
      waitingApplications: "Заявки на проверке",
      waitingPhotos: "Фото на проверке",
      profiles: "Профили",
      matches: "Пары",
      notifications: "Уведомления",
    },
    actions: {
      approve: "Одобрить",
      reject: "Отклонить",
      needInfo: "Нужна информация",
      hide: "Скрыть",
      useAnyway: "Оставить",
      requestNew: "Попросить новое фото",
      publish: "Опубликовать",
      unpublish: "Снять с публикации",
      delete: "Удалить",
      preview: "Просмотр",
      runMatching: "Запустить подбор",
      rerun: "Повторить подбор",
      addNote: "Добавить заметку",
      schedule: "Назначить",
      complete: "Завершить",
      saveProfile: "Сохранить профиль",
    },
    fields: {
      name: "Имя",
      city: "Город",
      about: "О человеке",
      note: "Личная заметка",
    },
    photo: {
      face: "Лицо видно",
      person: "Главный человек",
      quality: "Качество",
      yes: "да",
      no: "нет",
      decision: "Решение администратора",
      annotation: "Пометки проверки",
      unavailable: "Проверка ИИ недоступна. Просмотрите фото самостоятельно.",
    },
    empty: {
      applications: "Заявок пока нет.",
      profiles: "Профилей пока нет.",
      photos: "Фото пока нет.",
      matches: "Пар пока нет.",
      introductions: "Знакомств пока нет.",
      feedback: "Отзывов пока нет.",
      notifications: "Уведомлений пока нет.",
      history: "Действий администратора пока нет.",
      blog: "Черновиков блога пока нет.",
      users: "Пользователей пока нет.",
      notes: "Заметок пока нет.",
    },
    status: {
      new: "Новая",
      info_requested: "Нужна информация",
      approved: "Одобрена",
      rejected: "Отклонена",
      pending: "На проверке",
      public: "Виден",
      hidden: "Скрыт",
      draft: "Черновик",
      published: "Опубликован",
      proposed: "Предложена",
      saved: "Сохранена",
      AI_OK: "ИИ: норма",
      AI_WARNING: "ИИ: предупреждение",
      REVIEW_REQUIRED: "Нужна проверка",
      AI_UNAVAILABLE: "ИИ недоступен",
    },
    confirm: {
      published: "Статья опубликована.",
      unpublished: "Статья снята с публикации.",
      deleted: "Удалено.",
    },
    settingsHint: "Каждый администратор выбирает свой язык. Выбор сохраняется.",
  },
} as const;

export type AdminCopy = (typeof adminCopy)[AdminLocale];

export function statusLabel(t: AdminCopy, status?: string | null) {
  if (!status) return "—";
  const map = t.status as Record<string, string>;
  return map[status] || status.replace(/_/g, " ");
}
