export const miniCopy = {
  en: {
    loading: "Just a moment…",
    openFromTelegram: "Open this page from Telegram to continue.",
    continue: "Continue",
    back: "Back",
    submit: "Submit profile",
    save: "Save",
    edit: "Edit",
    addPhoto: "Add photo",
    remove: "Remove",
    mainPhoto: "Main photo",
    makeMain: "Use as main photo",
    stepName: "What should we call you?",
    stepAge: "How old are you?",
    stepPlace: "Where do you live?",
    stepAbout: "A few words about you",
    stepLooking: "What are you looking for?",
    stepWho: "Who would you like to meet?",
    stepPhotos: "Add a photo of you",
    stepReview: "Does this look right?",
    name: "Your name",
    age: "Your age",
    city: "City",
    country: "Country",
    about: "About you",
    photosHint: "One clear photo of you is enough to begin. You can add more later.",
    relationship: "A relationship",
    friendship: "Friendship",
    marriage: "Marriage",
    notSure: "Not sure yet",
    aMan: "A man",
    aWoman: "A woman",
    interested: "Interested",
    notForMe: "Not for me",
    noMatches: "No introductions yet. We will write when there is someone for you.",
    noPhotos: "Add a photo so we can get to know you.",
    submitted: "Thank you. Our team will look at your profile personally.",
    network: "We couldn't save your changes. Please try again.",
    profile: "My Profile",
    photos: "Photos",
    matches: "Matches",
    preferences: "Preferences",
    alerts: "Notifications",
    settings: "Settings",
    admin: "Admin",
    lookingFor: "Looking for",
    signOut: "Sign out",
    needPhoto: "Please add at least one photo.",
    needName: "Please add your name.",
  },
  es: {
    loading: "Un momento…",
    openFromTelegram: "Abre esta página desde Telegram para continuar.",
    continue: "Continuar",
    back: "Atrás",
    submit: "Enviar perfil",
    save: "Guardar",
    edit: "Editar",
    addPhoto: "Añadir foto",
    remove: "Quitar",
    mainPhoto: "Foto principal",
    makeMain: "Usar como principal",
    stepName: "¿Cómo te llamas?",
    stepAge: "¿Qué edad tienes?",
    stepPlace: "¿Dónde vives?",
    stepAbout: "Cuéntanos un poco de ti",
    stepLooking: "¿Qué buscas?",
    stepWho: "¿A quién te gustaría conocer?",
    stepPhotos: "Añade una foto tuya",
    stepReview: "¿Está bien así?",
    name: "Tu nombre",
    age: "Tu edad",
    city: "Ciudad",
    country: "País",
    about: "Sobre ti",
    photosHint: "Basta una foto clara tuya para empezar. Podrás añadir más después.",
    relationship: "Una relación",
    friendship: "Amistad",
    marriage: "Matrimonio",
    notSure: "Aún no lo sé",
    aMan: "Un hombre",
    aWoman: "Una mujer",
    interested: "Me interesa",
    notForMe: "No es para mí",
    noMatches: "Aún no hay presentaciones. Te escribiremos cuando haya alguien para ti.",
    noPhotos: "Añade una foto para que podamos conocerte.",
    submitted: "Gracias. Nuestro equipo mirará tu perfil en persona.",
    network: "No pudimos guardar los cambios. Inténtalo de nuevo.",
    profile: "Mi perfil",
    photos: "Fotos",
    matches: "Encuentros",
    preferences: "Preferencias",
    alerts: "Avisos",
    settings: "Ajustes",
    admin: "Admin",
    lookingFor: "Busco",
    signOut: "Salir",
    needPhoto: "Añade al menos una foto.",
    needName: "Añade tu nombre.",
  },
} as const;
